blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    ArticlesListView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleCreateView,
    ArticleDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("", ArticlesListView.as_view(), name="article_list"),
    path("view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("edit/<int:pk>", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete_article"),
]

nextgenstore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    CustomLoginView,
    UserCreateView,
    email_verification,
    password_reset,
    UserProfileUpdateView,
    UserProfileDetailView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", CustomLoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path("password-reset/", password_reset, name="password_reset"),
    path("profile/edit/", UserProfileUpdateView.as_view(), name="edit_profile"),
    path("profile/", UserProfileDetailView.as_view(), name="profile"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from catalog.utils import upload_to

BLANK_NULL_TRUE = {"blank": True, "null": True}


class User(AbstractUser):
    """
    Model for the user
    """

    username = None
    email = models.EmailField(unique=True, verbose_name="Email")
    phone = PhoneNumberField(verbose_name="Номер телефона", **BLANK_NULL_TRUE)
    avatar = models.ImageField(
        upload_to=upload_to, **BLANK_NULL_TRUE, verbose_name="Аватар"
    )
    country = models.CharField(max_length=50, **BLANK_NULL_TRUE, verbose_name="Страна")
    token = models.CharField(max_length=150, verbose_name="Токен", **BLANK_NULL_TRUE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from users.models import User


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Введите ваш Email"}
        ),
    )


class UserCreateForm(UserCreationForm):
    email = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Введите ваш Email"}
        ),
    )

    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Введите пароль"}
        ),
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(
            attrs={"class": "form-control", "placeholder": "Подтвердите пароль"}
        ),
    )

    class Meta:
        model = User
        fields = ["email", "password1", "password2"]


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email", "phone", "avatar", "country"]
        widgets = {
            "email": forms.EmailInput(
                attrs={"class": "form-control", "placeholder": "Введите email"}
            ),
            "phone": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Введите номер телефона"}
            ),
            "avatar": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "country": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Введите страну"}
            ),
        }


class UserProfileViewForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email", "phone", "avatar", "country"]
        widgets = {
            "email": forms.TextInput(
                attrs={"class": "form-control", "readonly": "readonly"}
            ),
            "phone": forms.TextInput(
                attrs={"class": "form-control", "readonly": "readonly"}
            ),
            "avatar": forms.ClearableFileInput(
                attrs={
                    "class": "form-control",
                    "readonly": "readonly",
                    "disabled": True,
                }
            ),
            "country": forms.TextInput(
                attrs={"class": "form-control", "readonly": "readonly"}
            ),
        }

users/views.py
import secrets

from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.contrib.auth.views import LoginView
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, DetailView

from users.forms import CustomAuthenticationForm, UserCreateForm, UserProfileForm
from users.models import User
from users.utils import (
    send_email_confirm,
    generate_random_password,
    send_email_reset_password,
)


class CustomLoginView(LoginView):
    form_class = CustomAuthenticationForm
    template_name = "login.html"


class UserCreateView(CreateView):
    model = User
    form_class = UserCreateForm
    template_name = "users/user_form.html"
    success_url = reverse_lazy("users:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f"http://{host}/users/email-confirm/{token}"
        send_email_confirm(url, user.email)

        messages.success(
            self.request,
            "Ссылка для подтверждения вашего email была отправлена на указанный адрес.",
        )
        return super().form_valid(form)


class UserProfileUpdateView(UpdateView):
    model = User
    form_class = UserProfileForm
    template_name = "users/user_profile_form.html"
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user


class UserProfileDetailView(DetailView):
    model = User
    template_name = "users/user_profile_detail.html"
    context_object_name = "user_profile"

    def get_object(self, queryset=None):
        return self.request.user


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()

    messages.success(
        request, "Ваш email был успешно подтвержден! Теперь вы можете войти в систему."
    )
    return redirect(reverse("users:login"))


def password_reset(request):
    if request.method == "POST":
        email = request.POST.get("email")
        try:
            user = User.objects.get(email=email)
            new_password = generate_random_password()
            user.password = make_password(new_password)
            user.save()

            send_email_reset_password(new_password, email)
            messages.success(
                request, "Новый пароль был отправлен на вашу электронную почту"
            )
            return redirect("users:login")
        except User.DoesNotExist:
            messages.error(request, "Пользователь с таким email не найден")

    return render(request, "users/password_reset.html")

users/templates/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4 g-4">
        <h1 class="text-center">Вход на сайт</h1>
        <p class="text-center">Введите ваш email и пароль для входа в систему</p>

        <div class="row g-4">
            <div class="col-md-6 offset-md-3">
                <form method="post">
                    {% csrf_token %}
                    {% if messages %}
                        <div class="container mt-4">
                            {% for message in messages %}
                                <div class="alert alert-{% if message.tags == 'error' %}danger{% elif message.tags == 'success' %}success{% endif %}">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <ul>
                                {% for field, errors in form.errors.items %}
                                    {% for error in errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                {% endfor %}
                            </ul>
                        </div>
                    {% endif %}

                    <div class="mb-3">
                        <label for="email" class="form-label">Ваш Email</label>
                        <input type="email" class="form-control" id="email" placeholder="Введите ваш Email"
                               name="username" required>
                    </div>
                    <div class="mb-3">
                        <label for="password" class="form-label">Пароль</label>
                        <input type="password" class="form-control" id="password" placeholder="Введите ваш пароль"
                               name="password" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </form>
                <p class="mt-3">
                    Еще не зарегистрированы? <a href="{% url 'users:register' %}">Зарегистрируйтесь</a>
                </p>
                <p class="mt-3">
                    Забыли пароль? <a href="{% url 'users:password_reset' %}">Сбросить пароль</a>
                </p>
            </div>
        </div>
    </div>
{% endblock %}