blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    ArticlesListView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleCreateView,
    ArticleDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("", ArticlesListView.as_view(), name="article_list"),
    path("view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("edit/<int:pk>", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete_article"),
]

nextgenstore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

from catalog.utils import upload_to
from catalog.models import BLANK_NULL_TRUE


class Article(models.Model):
    """
    Blog post model
    """

    title = models.CharField(max_length=150, verbose_name="заголовок")
    slug = models.CharField(max_length=150, **BLANK_NULL_TRUE)
    content = models.TextField(verbose_name="cодержимое статьи")
    preview = models.ImageField(
        upload_to=upload_to, verbose_name="превью", **BLANK_NULL_TRUE
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="дата создания")
    is_published = models.BooleanField(default=True, verbose_name="опубликовано")
    views_count = models.IntegerField(default=0, verbose_name="просмотры")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "статья"
        verbose_name_plural = "статьи"
        ordering = ("-created_at",)

blog/forms.py
from django import forms
from blog.models import Article


class ArticleUpdateForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "content", "preview", "is_published"]
        widgets = {
            "title": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите заголовок статьи",
                    "required": "required",
                    "id": "title",
                }
            ),
            "content": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "rows": 10,
                    "placeholder": "Введите содержимое статьи",
                    "required": "required",
                    "id": "content",
                }
            ),
            "preview": forms.ClearableFileInput(
                attrs={"class": "form-control", "id": "preview"}
            ),
            "is_published": forms.CheckboxInput(
                attrs={"class": "form-check-input", "id": "is_published"}
            ),
        }

blog/views.py
from django.urls import reverse_lazy
from pytils.translit import slugify
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView,
)

from blog.models import Article
from blog.forms import ArticleUpdateForm


class ArticlesListView(ListView):
    model = Article
    paginate_by = 10

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_published=True)
        return queryset


class ArticleDetailView(DetailView):
    model = Article

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleUpdateForm
    success_url = reverse_lazy("blog:article_list")

    def form_valid(self, form):
        if form.is_valid():
            item = form.save()
            item.slug = slugify(item.title)
            item.save()
        return super().form_valid(form)


class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleUpdateForm

    def get_success_url(self):
        return reverse_lazy("blog:article_detail", kwargs={"pk": self.object.pk})


class ArticleDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy("blog:article_list")

blog/templates/blog/article_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Подтверждение удаления</h5>
                        <p class="text-center">Вы уверены, что хотите удалить материал "{{ object.title }}"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'blog:article_list' %}" class="btn btn-warning ms-2">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_detail.html
<!-- templates/article_detail.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container-fluid my-5">
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    {% if object.preview %}
                        <img src="{{ object.preview.url }}" class="card-img-top" alt="{{ object.title }}">
                    {% endif %}
                    <div class="card-body">
                        <h1 class="card-title">{{ object.title }}</h1>
                        <p class="text-muted mb-4">Опубликовано: {{ object.created_at|date:"d F Y в H:i" }}</p>
                        <div class="card-text text-justify">
                            {{ object.content|safe }}
                        </div>
                    </div>
                    <div class="card-footer text-muted">
                        Просмотров: {{ object.views_count }}
                    </div>
                </div>
                <a href="{% url 'blog:article_list' %}" class="btn btn-primary">Назад к списку статей</a>
                <a class="btn btn-outline-warning" href="{% url 'blog:update_article' object.pk %}"
                   role="button">Редактировать</a>
                <a class="btn btn-outline-danger" href="{% url 'blog:delete_article' object.pk %}" role="button">Удалить</a>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/article_form.html
{% extends 'base.html' %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-3">
            <label for="title" class="form-label">Заголовок статьи</label>
            {{ form.title }}
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">Содержимое статьи</label>
            {{ form.content }}
        </div>
        <div class="mb-3">
            <label for="preview" class="form-label">Превью</label>
            {{ form.preview }}
        </div>
        <div class="mb-3 form-check">
            {{ form.is_published }}
            <label class="form-check-label" for="is_published">
                Опубликовано
            </label>
        </div>
        <button type="submit" class="btn btn-primary">Сохранить изменения</button>
        <a href="{% url 'blog:article_list' %}" class="btn btn-outline-primary">Назад к списку статей</a>
    </form>
{% endblock %}

blog/templates/blog/article_list.html
{% extends 'base.html' %}
{% load article_filters %}
{% load product_filters %}
{% load static %}
{% block content %}
    <div class="container">
        <h2 class="text-center">Добро пожаловать в наш блог!</h2>
        <p class="text-center">Здесь вы найдете интересные статьи, полезные советы и новинки в мире технологий,
            обзоры гаджетов и многое другое. Мы стремимся делиться с вами самыми актуальными и полезными
            материалами,
            чтобы вы всегда оставались в курсе событий.</p>
        <p class="text-center">Погружайтесь в чтение и открывайте для себя мир новых возможностей вместе с нами!</p>
    </div>
    <div class="mb-3">
        <a class="btn btn-primary" href="{% url 'blog:create_article' %}" role="button">Создать запись</a>
    </div>
    {% for object in object_list %}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-3">
                    <img src="{{ object|preview_url }}" class="fixed-img-size image-container" alt="{{ object.title }}">
                </div>
                <div class="col-md-9 d-flex flex-column">
                    <div class="card-body">
                        <h5 class="card-title">{{ object.title }}</h5>
                        <p class="text-muted mb-0">{{ object.created_at|date:"d.m.Y H.i" }}</p>
                        <p class="card-text mb-0">{{ object.content|truncate_chars|safe }}</p>
                    </div>
                    <div class="d-flex justify-content-between align-items-center px-3 py-2">
                        <div class="btn-group">
                            <a class="btn btn-outline-primary me-1" href="{% url 'blog:article_detail' object.pk %}"
                               role="button">Читать</a>
                            <a class="btn btn-outline-warning me-1" href="{% url 'blog:update_article' object.pk %}"
                               role="button">Редактировать</a>
                            <a class="btn btn-outline-danger" href="{% url 'blog:delete_article' object.pk %}"
                               role="button">Удалить</a>
                        </div>
                        <p class="text-muted mb-0 small">Просмотров: {{ object.views_count }}</p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    {% include 'catalog/includes/inc_pagination.html' %}
{% endblock %}