blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    ArticlesListView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleCreateView,
    ArticleDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("", ArticlesListView.as_view(), name="article_list"),
    path("view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("edit/<int:pk>", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete_article"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import (
    ProductListView,
    ContactTemplateView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    MainTemplateView,
    ProductDeleteView,
)
from catalog.apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path("", MainTemplateView.as_view(), name="home"),
    path("contact/", ContactTemplateView.as_view(), name="contact"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("products/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/edit/<int:pk>/", ProductUpdateView.as_view(), name="product_edit"),
    path("products/delete/<int:pk>", ProductDeleteView.as_view(), name="product_delete"),
]

nextgenstore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import (
    CustomLoginView,
    UserCreateView,
    email_verification,
    password_reset,
    UserProfileUpdateView,
    UserProfileDetailView,
)

app_name = UsersConfig.name

urlpatterns = [
    path("login/", CustomLoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email_confirm"),
    path("password-reset/", password_reset, name="password_reset"),
    path("profile/edit/", UserProfileUpdateView.as_view(), name="edit_profile"),
    path("profile/", UserProfileDetailView.as_view(), name="profile"),
]

catalog/models.py
from decimal import Decimal
from django.db import models
from catalog.utils import upload_to
from users.models import User

BLANK_NULL_TRUE = {"blank": True, "null": True}


class Category(models.Model):
    """
    A model for storing product categories.
    """

    name = models.CharField(max_length=50, verbose_name="Наименование категории")
    description = models.TextField(verbose_name="Описание категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    """
    A model for storing information about products.
    """

    name = models.CharField(max_length=50, verbose_name="Наименование товара")
    description = models.TextField(**BLANK_NULL_TRUE, verbose_name="Описание товара")
    preview = models.ImageField(
        **BLANK_NULL_TRUE, upload_to=upload_to, verbose_name="Изображение товара"
    )
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
        verbose_name="Цена за покупку",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец товара",
        **BLANK_NULL_TRUE,
        on_delete=models.SET_NULL,
    )
    is_published = models.BooleanField(default=False, verbose_name="Опубликован")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name", "-price", "created_at", "-updated_at"]
        permissions = [
            ("can_unpublish_product", "Может отменить публикацию продукта"),
            ("can_change_description", "Может изменить описание продукта"),
            ("can_change_category", "Может изменить категорию продукта"),
        ]


class ContactInfo(models.Model):
    """
    Model to store static contact information.
    """

    phone = models.CharField(max_length=20, verbose_name="Номер телефона")
    email = models.EmailField(verbose_name="Почта")
    address = models.TextField(verbose_name="Адрес")

    def __str__(self):
        return f"{self.phone}" f"{self.email}" f"{self.address}"

    class Meta:
        verbose_name = "Контактная информация"
        verbose_name_plural = "Контактные информации"


class Version(models.Model):
    """
    Model for storing version product
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=50, verbose_name="Номер версии")
    version_name = models.CharField(max_length=100, verbose_name="Название версии")
    is_active = models.BooleanField(default=False, verbose_name="Активность версии")

    def __str__(self):
        return f"{self.version_name} - ({self.version_number})"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    forbidden_words = [
        "казино",
        "криптовалюта",
        "крипта",
        "биржа",
        "дешево",
        "бесплатно",
        "обман",
        "полиция",
        "радар",
    ]

    class Meta:
        model = Product
        fields = [
            "name",
            "description",
            "preview",
            "category",
            "price",
            "is_published",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите наименование товара",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите описание товара",
                }
            ),
            "preview": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-select"}),
            "price": forms.NumberInput(attrs={"class": "form-control"}),
            "is_published": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if any(word in name.lower() for word in self.forbidden_words):
            raise ValidationError(
                "Название товара не должно содержать запрещенные слова"
            )
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in self.forbidden_words):
            raise ValidationError("Описание не должно содержать запрещенные слова")
        return description


class ProductModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("description", "category", "is_published")
        widgets = {
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите описание товара",
                }
            ),
            "category": forms.Select(attrs={"class": "form-select"}),
            "is_published": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"
        widgets = {
            "product": forms.Select(attrs={"class": "form-select"}),
            "version_number": forms.TextInput(attrs={"class": "form-control"}),
            "version_name": forms.TextInput(attrs={"class": "form-control"}),
            "is_active": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

catalog/views.py
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.mixins import CustomLoginRequiredMixin
from catalog.models import Product, ContactInfo, Version, Category
from catalog.services import get_categories_from_cache


class MainTemplateView(TemplateView):
    template_name = "catalog/index.html"


class ContactTemplateView(TemplateView):
    template_name = "catalog/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contact_info"] = ContactInfo.objects.first()
        context["form"] = None
        return context

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class ProductListView(ListView):
    model = Product
    paginate_by = 6
    ordering = ["-created_at"]

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        category = self.request.GET.get('category')
        if category:
            queryset = queryset.filter(category__name=category)
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = get_categories_from_cache()
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CustomLoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Создание товара"
        VersionFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(self.request.POST)
        else:
            context_data["formset"] = VersionFormset()
        return context_data

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context["formset"]
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Редактирование товара"
        VersionFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1, can_delete=True
        )
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["formset"]
        if form.is_valid() and formset.is_valid():
            versions = [
                form for form in formset if form.cleaned_data.get("is_active", False)
            ]
            if len(versions) > 1:
                form.add_error(
                    None, "У продукта не может быть более одной активной версии."
                )
                return self.form_invalid(form)
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        return self.form_invalid(form)

    def get_form_class(self):
        required_perms = [
            "catalog.can_unpublish_product",
            "catalog.can_change_description",
            "catalog.can_change_category",
        ]
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ProductForm
        if user.has_perms(required_perms):
            return ProductModeratorForm
        raise PermissionDenied

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if (
            self.request.user == self.object.owner
            or self.request.user.groups.filter(name="moderator").exists()
            or self.request.user.is_superuser
        ):
            return self.object

        raise PermissionDenied


class ProductDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

catalog/templates/catalog/includes/inc_nav_footer.html
{% load static %}
<div class="row">
    <div class="col-12 col-md">
        <img class="mb-2" src="{% static 'image/logo.webp' %}" alt="" width="90" height="85">
        <small class="d-block mb-3 text-body-secondary">&copy; 2017–{% now 'Y' %}</small>
    </div>
    <div class="col-6 col-md">
        <h5>Продукты и услуги</h5>
        <ul class="list-unstyled text-small">
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Смартфоны</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Ноутбуки</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Аксессуары</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Умные устройства</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Игровые консоли</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>Полезные ссылки</h5>
        <ul class="list-unstyled text-small">
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">О нас</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Контакты</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Доставка и возврат</a></li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Политика конфиденциальности</a>
            </li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Условия использования</a></li>
        </ul>
    </div>
    <div class="col-6 col-md">
        <h5>Контакты</h5>
        <ul class="list-unstyled text-small">
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Телефон: +7 (123) 456-78-90</a>
            </li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Email: support@nextgenstore.ru</a>
            </li>
            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Адрес: ул. Примерная, 123,
                Москва</a></li>
        </ul>
    </div>
</div>

catalog/templates/catalog/includes/inc_nav_menu.html
{% load static %}
<div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="{% url 'catalog:product_list' %}"
       class="d-flex flex-column align-items-start link-body-emphasis text-decoration-none">
        <div class="d-flex align-items-center">
            <img class="mb-2" src="{% static 'image/logo.webp' %}" alt="" width="90" height="85">
            <span class="fs-2 ms-2">NextGen Store</span>
        </div>
    </a>
    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:home' %}">Главная</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:product_list' %}">Каталог</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'blog:article_list' %}">Блог</a>
        <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'catalog:contact' %}">Контакты</a>
        {% if user.is_authenticated %}
            <a class="me-3 py-2 link-body-emphasis text-decoration-none" href="{% url 'users:profile' %}">Профиль</a>
            <form action="{% url 'users:logout' %}" method="post" class="d-inline">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-primary">Выход
                </button>
            </form>
        {% else %}
            <a class="btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
        {% endif %}

    </nav>
</div>

catalog/templates/catalog/includes/inc_pagination.html
<nav aria-label="Pagination">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Назад</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Назад</a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                <li class="page-item {% if page_obj.number == num %}active{% endif %}">
                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Вперед</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link">Вперед</a>
                </li>
            {% endif %}
        </ul>
    </nav>