blog/urls.py
from django.urls import path

from blog.apps import BlogConfig
from blog.views import (
    ArticlesListView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleCreateView,
    ArticleDeleteView,
)


app_name = BlogConfig.name

urlpatterns = [
    path("", ArticlesListView.as_view(), name="article_list"),
    path("view/<int:pk>", ArticleDetailView.as_view(), name="article_detail"),
    path("create/", ArticleCreateView.as_view(), name="create_article"),
    path("edit/<int:pk>", ArticleUpdateView.as_view(), name="update_article"),
    path("delete/<int:pk>/", ArticleDeleteView.as_view(), name="delete_article"),
]

catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import (
    ProductListView,
    ContactTemplateView,
    ProductDetailView,
    ProductCreateView,
    ProductUpdateView,
    MainTemplateView,
    ProductDeleteView,
)
from catalog.apps import CatalogConfig


app_name = CatalogConfig.name

urlpatterns = [
    path("", MainTemplateView.as_view(), name="home"),
    path("contact/", ContactTemplateView.as_view(), name="contact"),
    path("products/", ProductListView.as_view(), name="product_list"),
    path("products/<int:pk>/", cache_page(60)(ProductDetailView.as_view()), name="product_detail"),
    path("products/create/", ProductCreateView.as_view(), name="product_create"),
    path("products/edit/<int:pk>/", ProductUpdateView.as_view(), name="product_edit"),
    path("products/delete/<int:pk>", ProductDeleteView.as_view(), name="product_delete"),
]

nextgenstore/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("users/", include("users.urls", namespace="users")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from decimal import Decimal
from django.db import models
from catalog.utils import upload_to
from users.models import User

BLANK_NULL_TRUE = {"blank": True, "null": True}


class Category(models.Model):
    """
    A model for storing product categories.
    """

    name = models.CharField(max_length=50, verbose_name="Наименование категории")
    description = models.TextField(verbose_name="Описание категории")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"
        ordering = ["name"]


class Product(models.Model):
    """
    A model for storing information about products.
    """

    name = models.CharField(max_length=50, verbose_name="Наименование товара")
    description = models.TextField(**BLANK_NULL_TRUE, verbose_name="Описание товара")
    preview = models.ImageField(
        **BLANK_NULL_TRUE, upload_to=upload_to, verbose_name="Изображение товара"
    )
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        default=Decimal("0.00"),
        verbose_name="Цена за покупку",
    )
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец товара",
        **BLANK_NULL_TRUE,
        on_delete=models.SET_NULL,
    )
    is_published = models.BooleanField(default=False, verbose_name="Опубликован")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Товар"
        verbose_name_plural = "Товары"
        ordering = ["name", "-price", "created_at", "-updated_at"]
        permissions = [
            ("can_unpublish_product", "Может отменить публикацию продукта"),
            ("can_change_description", "Может изменить описание продукта"),
            ("can_change_category", "Может изменить категорию продукта"),
        ]


class ContactInfo(models.Model):
    """
    Model to store static contact information.
    """

    phone = models.CharField(max_length=20, verbose_name="Номер телефона")
    email = models.EmailField(verbose_name="Почта")
    address = models.TextField(verbose_name="Адрес")

    def __str__(self):
        return f"{self.phone}" f"{self.email}" f"{self.address}"

    class Meta:
        verbose_name = "Контактная информация"
        verbose_name_plural = "Контактные информации"


class Version(models.Model):
    """
    Model for storing version product
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    version_number = models.CharField(max_length=50, verbose_name="Номер версии")
    version_name = models.CharField(max_length=100, verbose_name="Название версии")
    is_active = models.BooleanField(default=False, verbose_name="Активность версии")

    def __str__(self):
        return f"{self.version_name} - ({self.version_number})"

    class Meta:
        verbose_name = "Версия"
        verbose_name_plural = "Версии"

catalog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from catalog.models import Product, Version


class ProductForm(forms.ModelForm):
    forbidden_words = [
        "казино",
        "криптовалюта",
        "крипта",
        "биржа",
        "дешево",
        "бесплатно",
        "обман",
        "полиция",
        "радар",
    ]

    class Meta:
        model = Product
        fields = [
            "name",
            "description",
            "preview",
            "category",
            "price",
            "is_published",
        ]
        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите наименование товара",
                }
            ),
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите описание товара",
                }
            ),
            "preview": forms.ClearableFileInput(attrs={"class": "form-control"}),
            "category": forms.Select(attrs={"class": "form-select"}),
            "price": forms.NumberInput(attrs={"class": "form-control"}),
            "is_published": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

    def clean_name(self):
        name = self.cleaned_data.get("name")
        if any(word in name.lower() for word in self.forbidden_words):
            raise ValidationError(
                "Название товара не должно содержать запрещенные слова"
            )
        return name

    def clean_description(self):
        description = self.cleaned_data.get("description")
        if any(word in description.lower() for word in self.forbidden_words):
            raise ValidationError("Описание не должно содержать запрещенные слова")
        return description


class ProductModeratorForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("description", "category", "is_published")
        widgets = {
            "description": forms.Textarea(
                attrs={
                    "class": "form-control",
                    "placeholder": "Введите описание товара",
                }
            ),
            "category": forms.Select(attrs={"class": "form-select"}),
            "is_published": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"
        widgets = {
            "product": forms.Select(attrs={"class": "form-select"}),
            "version_number": forms.TextInput(attrs={"class": "form-control"}),
            "version_name": forms.TextInput(attrs={"class": "form-control"}),
            "is_active": forms.CheckboxInput(attrs={"class": "form-check-input"}),
        }

catalog/views.py
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.forms import inlineformset_factory
from django.views.generic import (
    TemplateView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView,
)
from catalog.forms import ProductForm, VersionForm, ProductModeratorForm
from catalog.mixins import CustomLoginRequiredMixin
from catalog.models import Product, ContactInfo, Version, Category
from catalog.services import get_categories_from_cache


class MainTemplateView(TemplateView):
    template_name = "catalog/index.html"


class ContactTemplateView(TemplateView):
    template_name = "catalog/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contact_info"] = ContactInfo.objects.first()
        context["form"] = None
        return context

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)


class ProductListView(ListView):
    model = Product
    paginate_by = 6
    ordering = ["-created_at"]

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        category = self.request.GET.get('category')
        if category:
            queryset = queryset.filter(category__name=category)
        queryset = queryset.filter(is_published=True)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = get_categories_from_cache()
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductCreateView(CustomLoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Создание товара"
        VersionFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1
        )
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(self.request.POST)
        else:
            context_data["formset"] = VersionFormset()
        return context_data

    def form_valid(self, form):
        form.instance.owner = self.request.user
        context = self.get_context_data()
        formset = context["formset"]
        if formset.is_valid():
            self.object = form.save()
            formset.instance = self.object
            formset.save()
        return super().form_valid(form)


class ProductUpdateView(CustomLoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy("catalog:product_list")

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data["title"] = "Редактирование товара"
        VersionFormset = inlineformset_factory(
            Product, Version, form=VersionForm, extra=1, can_delete=True
        )
        if self.request.method == "POST":
            context_data["formset"] = VersionFormset(
                self.request.POST, instance=self.object
            )
        else:
            context_data["formset"] = VersionFormset(instance=self.object)
        return context_data

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context["formset"]
        if form.is_valid() and formset.is_valid():
            versions = [
                form for form in formset if form.cleaned_data.get("is_active", False)
            ]
            if len(versions) > 1:
                form.add_error(
                    None, "У продукта не может быть более одной активной версии."
                )
                return self.form_invalid(form)
            self.object = form.save()
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        return self.form_invalid(form)

    def get_form_class(self):
        required_perms = [
            "catalog.can_unpublish_product",
            "catalog.can_change_description",
            "catalog.can_change_category",
        ]
        user = self.request.user
        if user == self.object.owner or user.is_superuser:
            return ProductForm
        if user.has_perms(required_perms):
            return ProductModeratorForm
        raise PermissionDenied

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        if (
            self.request.user == self.object.owner
            or self.request.user.groups.filter(name="moderator").exists()
            or self.request.user.is_superuser
        ):
            return self.object

        raise PermissionDenied


class ProductDeleteView(CustomLoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy("catalog:product_list")

catalog/templates/catalog/contact.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4 g-4">
        <h1 class="text-center">Контактная информация</h1>
        <p class="text-center">Мы готовы ответить на ваши вопросы и помочь вам. Свяжитесь с нами любым удобным
            способом.</p><br>

        <div class="row g-4">
            <div class="col-md-6">
                <h2 class="section-heading">Наши контактные данные</h2>
                <p><strong>Телефон:</strong> {{ contact_info.phone }}</p>
                <p><strong>Электронная почта:</strong><a
                        href="mailto:{{ contact_info.email }}">   {{ contact_info.email }}</a>
                </p>
                <p><strong>Адрес:</strong> {{ contact_info.address }}</p>
            </div>
            <div class="col-md-6">
                <h2 class="section-heading">Связаться с нами</h2>
                <p>Оставьте ваше сообщение, и мы свяжемся с вами в ближайшее время.</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name" class="form-label">Ваше имя</label>
                        <input type="text" class="form-control" id="name" placeholder="Введите ваше имя" required
                               name="name">
                    </div>
                    <div class="mb-3">
                        <label for="email" class="form-label">Ваш Email адрес</label>
                        <input type="email" class="form-control" id="email" placeholder="Введите ваш Email" required
                               name="email">
                    </div>
                    <div class="mb-3">
                        <label for="message" class="form-label">Ваше сообщение</label>
                        <textarea class="form-control" id="message" rows="4" placeholder="Введите ваше сообщение"
                                  required name="message"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <div class="content text-center mt-5">
            <h1>Добро пожаловать на наш сайт NextGen Store</h1>
            <p>Здесь вы найдете каталог новейших товаров и интересный блог, который поможет вам оставаться в курсе событий в мире технологий и современных решений.</p>
        </div>

        <div class="row mt-4 mb-5">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-center">Каталог товаров</h2>
                        <p class="card-text">Ознакомьтесь с нашим каталогом, где представлены лучшие продукты, которые соответствуют вашим требованиям.</p>
                        <div class="text-center mt-4">
                            <a href="{% url 'catalog:product_list' %}" class="btn btn-primary">Перейти к каталогу</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h2 class="card-title text-center">Блог</h2>
                        <p class="card-text">Читайте наши последние публикации и оставайтесь в курсе новейших тенденций и советов, которые помогут вам в выборе товаров и в жизни.</p>
                        <div class="text-center mt-4">
                            <a href="{% url 'blog:article_list' %}" class="btn btn-primary">Перейти в блог</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title text-center">Подтверждение удаления</h5>
                        <p class="text-center">Вы уверены, что хотите удалить товар "{{ object.name }}"?</p>
                        <form method="post">
                            {% csrf_token %}
                            <div class="text-center">
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'catalog:product_list' %}" class="btn btn-warning ms-2">Отмена</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_detail.html
{% extends 'base.html' %}
{% load product_filters %}
{% block content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ object | preview_url }}" class="img-fluid" alt="{{ object.name }}"
                     style="background-color: white;">
            </div>
            <div class="col-md-6">
                <h1>{{ object.name }}</h1>
                {% if object.owner %}
                    <div class="card-footer text-muted">
                        Создано: {{ object.owner }}
                    </div>
                {% endif %}
                <p class="lead">{{ object.price }} руб.</p>
                <p>{{ object.description }}</p>
                <div class="d-flex">
                    <a href="#" class="btn btn-primary me-2">Добавить в корзину</a>
                    <a href="#" class="btn btn-secondary">Купить сейчас</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5">
        <form method="post" enctype="multipart/form-data">
            <h2 class="mt-4 text-center">{{ title }}</h2>
            {% csrf_token %}
            {% for error in form.non_field_errors %}
                <div class="alert alert-danger">{{ error }}</div>
            {% endfor %}
            <div class="row">
                <div class="col-md-6">
                    <h3 class="mt-4">Товар</h3>
                    <div class="mb-3">
                        <label for="name" class="form-label">Наименование товара</label>
                        {{ form.name }}
                        {% for error in form.name.errors %}
                            <br>
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Описание товара</label>
                        {{ form.description }}
                        {% for error in form.description.errors %}
                            <br>
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>
                    <div class="mb-3">
                        <label for="preview" class="form-label">Изображение товара</label>
                        {{ form.preview }}
                    </div>
                    <div class="mb-3">
                        <label for="category" class="form-label">Категория</label>
                        {{ form.category }}
                    </div>
                    <div class="mb-3">
                        <label for="price" class="form-label">Цена</label>
                        {{ form.price }}
                    </div>
                    <div class="mb-3 form-check">
                        {{ form.is_published }}
                        <label class="form-check-label" for="{{ form.is_published.id_for_label }}">
                            Опубликовано
                        </label>
                        {% for error in form.is_published.errors %}
                            <div class="alert alert-danger">{{ error }}</div>
                        {% endfor %}
                    </div>

                    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                    <a href="{% url 'catalog:product_list' %}" class="btn btn-outline-primary">Назад к списку товаров</a>
                </div>
                <div class="col-md-6">
                    <h3 class="mt-4">Версии продукта</h3>
                    {{ formset.management_form }}
                    {% for form in formset.forms %}
                        <div class="border p-3 mb-3">
                            {{ form.id }}
                            <div class="mb-3">
                                <label for="version_number" class="form-label">Номер версии</label>
                                {{ form.version_number }}
                            </div>
                            <div class="mb-3">
                                <label for="version_name" class="form-label">Название версии</label>
                                {{ form.version_name }}
                            </div>
                            <div class="d-flex">
                                <div class="mb-3 form-check align-items-center">
                                    {{ form.is_active }}
                                    <label class="form-check-label"
                                           for="{{ form.is_active.id_for_label }}">Активная</label>
                                    {% for error in form.is_active.errors %}
                                        <div class="alert alert-danger">{{ error }}</div>
                                    {% endfor %}
                                </div>
                                {% if form.instance.pk %}
                                    <div class="mb-3 form-check align-items-center">
                                        {{ form.DELETE }}
                                        <label class="form-check-label text-danger"
                                               for="{{ form.DELETE.id_for_label }}"> Удалить</label>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

catalog/templates/catalog/product_list.html
{% extends 'base.html' %}
{% load product_filters %}
{% load moderator_only %}

{% block content %}
    <div class="container">
        <div class="content">
            <h1>Добро пожаловать в NextGenStore</h1>
            <p>Ваш портал в мир высоких технологий</p>
            <h2>Откройте для себя новейшие технологии</h2>
            <p>
                Мы предлагаем новейшие гаджеты и устройства, которые помогут вам идти в ногу с будущим. Здесь вы
                найдёте всё, что нужно для комфортной и современной жизни:
            </p>
            <ul>
                <li><strong>Смартфоны</strong> с передовыми функциями</li>
                <li><strong>Ноутбуки</strong> для работы и развлечений</li>
                <li><strong>Умные устройства</strong> для вашего дома</li>
                <li><strong>Игровые консоли</strong> и аксессуары</li>
            </ul>
            <p>
                Оцените преимущества высококачественной электроники по доступным ценам с быстрой доставкой и
                отличным сервисом. <strong>NextGenStore</strong> — инновации, которые всегда рядом.
            </p>
        </div>
    </div>

    <h2 class="text-center md-3">Товары</h2><br>
    <div class="mb-3">
        <a class="btn btn-primary" href="{% url 'catalog:product_create' %}" role="button">Добавить продукт</a>
    </div>
    <div class="mb-3">
        <a href="{% url 'catalog:product_list' %}"
           class="btn {% if not request.GET.category or request.GET.category == 'all' %}btn-primary{% else %}btn-outline-primary{% endif %}">
            Все
        </a>
        {% for category in categories %}
            <a href="?category={{ category.name }}"
               class="btn {% if request.GET.category == category.name %}btn-primary{% else %}btn-outline-primary{% endif %}">
                {{ category.name }}
            </a>
        {% endfor %}
    </div>
    <div class="row row-cols-1 row-cols-md-3 mb-4 g-4 text-center">
        {% for object in object_list %}
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="image-container">
                        <img src="{{ object|preview_url }}" class="fixed-img-size" alt="{{ object.name }}">
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ object.name }}</h5>
                        <p class="card-text">{{ object.description|slice:":100" }}...</p>
                        {% for version in object.version_set.all %}
                            {% if version.is_active %}
                                <p class="card-text">Версия: {{ version.version_number }}</p>
                            {% endif %}
                        {% endfor %}
                        <div class="btn-group d-flex justify-content-center mb-2">
                            <a class="btn btn-outline-primary me-1" href="{% url 'catalog:product_detail' object.pk %}"
                               role="button">Подробнее</a>
                            <a class="btn btn-outline-success" href="#" role="button">{{ object.price }}</a>
                        </div>
                        {% if user == object.owner or user|has_required_perms %}
                            <div class="btn-group d-flex justify-content-center">
                                <a class="btn btn-outline-warning me-1"
                                   href="{% url 'catalog:product_edit' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-outline-danger" href="{% url 'catalog:product_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% include 'catalog/includes/inc_pagination.html' %}
{% endblock %}